"""edit task and project table to remove unused status

Revision ID: a22c19b15d0b
Revises: 12843f0a8d2b
Create Date: 2025-02-11 22:33:12.932458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22c19b15d0b'
down_revision: Union[str, None] = '12843f0a8d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_tasks', sa.Column('amount_due', sa.Float(), nullable=False))
    op.alter_column('project_tasks', 'notes',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_column('project_tasks', 'debt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_tasks', sa.Column('debt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('project_tasks', 'notes',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('project_tasks', 'amount_due')
    # ### end Alembic commands ###
