"""Set current_assignee default to None

Revision ID: cd46242594c5
Revises: 
Create Date: 2025-03-02 13:36:27.322420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd46242594c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_tasks', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_tasks', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('project_tasks', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('projects', 'current_assignee',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('projects', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tasks', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('projects', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('projects', 'current_assignee',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_tasks', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('project_tasks', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('project_tasks', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
